API para Periodos
Mercap/okr-api pull request #11
Opened 2019-05-10 15:21 UTC by jvanecek

Issue #9

2019-05-13 16:15 UTC, nchillo submitted a review, later dismissed

2019-05-14 17:16 UTC, gcotelli requested changes

2019-05-14 17:16 UTC, gcotelli commented on source/OKR-Tests/KeyResultTest.class.st
> +		withExceptionDo: [ :signal |
Buoy-SUnit includes extensions to test the message text of a raised exception

2019-05-15 00:11 UTC, serpi90 approved these changes

2019-05-15 00:18 UTC, serpi90 approved these changes

2019-05-15 14:11 UTC, gcotelli approved these changes

2019-05-15 14:11 UTC, merged