9 api para periodos POST /periods
Mercap/okr-api pull request #15
Opened 2019-05-15 00:20 UTC by serpi90

Part of #9

2019-05-15 20:08 UTC, gcotelli requested changes

2019-05-15 20:08 UTC, gcotelli commented on source/OKR-Model/PeriodRESTfulControllerSpecification.class.st
> +	 -jmaestri"
Eliminar hackazo.. pragmaticamente yo usaría el mismo media type que para no colección

2019-05-16 00:38 UTC, serpi90 commented on source/OKR-Model/PeriodRESTfulControllerSpecification.class.st
> +	 -jmaestri"
Se cambia para usar el mismo:
- por simplicidad
- hasta que se corriga https://github.com/ba-st/Stargate/issues/13 no vale la pena usar ambos.

2019-05-16 15:51 UTC, gcotelli approved these changes

2019-05-16 16:29 UTC, jvanecek approved these changes

2019-05-16 16:30 UTC, merged